spring.application.name=synccarreira-api

spring.profiles.active=${APP_PROFILE:prod}

spring.jpa.open-in-view=false

security.client-id=${CLIENT_ID:synccarreira-front-id}
security.client-secret=${CLIENT_SECRET:synccarreira-project-2026}

security.jwt.duration=${JWT_DURATION:18000}
