spring.datasource.url=jdbc:mysql://synccarreiradb.cy3eq80kiwd7.us-east-1.rds.amazonaws.com:3306/synccarreiradb
spring.datasource.username=admin
spring.datasource.password=projeto##CarrEira386!

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

cors.origins=http://seu-frontend.com

security.client-id=synccarreira-front-id
security.client-secret=synccarreira-project-2026
security.jwt.duration=18000